name: "CI setup"
description: "Setup NodeJS and PNPM"

inputs:
  node-version:
    description: "Node version"
    default: 18.14.1
  pnpm-version:
    description: "PNPM version"
    default: latest

runs:
  using: "composite"
  steps:
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    - uses: pnpm/action-setup@v2
      name: Install pnpm
      with:
        version: ${{ inputs.pnpm-version }}
        run_install: false

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Turbo Cache
      id: turbo-cache
      uses: actions/cache@v2
      with:
          path: |
            .turbo
            design-system/react/.turbo
            design-system/css/.turbo
            design-system/tokens/.turbo
            stitches/core/.turbo
            stitches/react/.turbo
          key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
              turbo-${{ github.job }}-${{ github.ref_name }}-

    - name: Install dependencies
      run: pnpm install
      shell: bash
