name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.0.2
          run_install: true

      - name: Lint, Test & Build Storybook
        run: |
          pnpm lint
          pnpm test
          cd ./design-system/react
          pnpm build:storybook

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          clean: true
          branch: gh-pages
          folder: design-system/react/storybook-static
