name: Build and Deploy

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: CI Setup
        uses: ./.github/actions/ci-setup

      - name: Audit, Lint & Test
        uses: ./.github/actions/ci-checks

      - name: Build Storybook
        run: |
          cd ./design-system/react
          pnpm build:storybook

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          clean: true
          branch: gh-pages
          folder: design-system/react/storybook-static
