name: "PR Checks"

on:
  pull_request:
    types: [opened, synchronize, edited, closed]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  COVERAGE_FILE: ./coverage/report.json

jobs:
  validate-title:
    name: Validate PR Title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  changesets:
    name: Changeset Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # need this to get full git-history/clone in order to build changelogs and check changesets
          fetch-depth: 0

      - uses: ./.github/actions/ci-setup
      - run: pnpm changeset status --since=origin/master

  audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/ci-setup
      - run: pnpm audit --prod

  lint-and-test:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/ci-setup
      - run: |
          pnpm ts:check
          pnpm lint

  test:
    name: Tests with coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/ci-setup
      - name: Checking PR Number
        uses: jwalton/gh-find-current-pr@v1
        id: findPr

      - name: Run Jest Tests
        run: |
          pnpm test -- --outputFile="${{ env.COVERAGE_FILE }}"

      - name: Publish coverage
        uses: ArtiomTr/jest-coverage-report-action@v2
        if: ${{ steps.findPr.outputs.number }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          package-manager: pnpm
          annotations: failed-tests
          test-script: pnpm test
          working-directory: ./design-system/react
          prnumber: ${{ steps.findPr.outputs.number }}
          skip-test: all
          coverage-file: ${{ env.COVERAGE_FILE }}
          base-coverage-file: ${{ env.COVERAGE_FILE }}
