name: "Release"

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-storybook:
    name: Build Storybook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/ci-setup
      - run: pnpm build

      - name: Build Storybook
        run: |
          cd ./design-system/react
          pnpm build:storybook

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          clean: true
          branch: gh-pages
          folder: design-system/react/storybook-static

  release-changesets:
    name: Changesets Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # need this to get full git-history/clone in order to build changelogs and check changesets
          fetch-depth: 0

      - name: CI Setup
        uses: ./.github/actions/ci-setup

      - name: Configure npm
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Ensure NPM access
        run: npm whoami
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Setup git user (for changelog step)
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Build
        run: pnpm build

      - name: Create Release Pull Request or Publish to NPM
        id: changesets
        uses: FuelLabs/changesets-action@main
        with:
          publish: pnpm changeset:release
          commit: "ci(changesets): versioning packages"
          title: "ci(changesets): versioning packages"
          createGithubReleases: aggregate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Release to @dev tag
        if: steps.changesets.outputs.published != 'true'
        run: |
          git checkout master
          pnpm changeset version --snapshot dev
          pnpm changeset publish --tag dev
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
