name: "Release"

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Changesets Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: CI Setup
        uses: ./.github/actions/ci-setup

      - name: Ensure NPM access
        run: npm whoami
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Configure npm
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          EOF
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Setup git user (for changelog step)
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Build
        run: pnpm build

      - name: Create Release Pull Request or Publish to NPM
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm changeset:release
          commit: "ci(changesets): versioning packages"
          title: "ci(changesets): versioning packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Release to @dev tag
        if: steps.changesets.outputs.published != 'true'
        run: |
          pnpm exec changeset version --snapshot dev
          pnpm exec changeset publish --tag dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build Storybook
        run: |
          cd ./design-system/react
          pnpm build:storybook

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          clean: true
          branch: gh-pages
          folder: design-system/react/storybook-static
