name: "Release"

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  release-changesets:
    name: Changesets Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # need this to get full git-history/clone in order to build changelogs and check changesets
          fetch-depth: 0

      - id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1.0.3
        with:
          version: 2
          verbose: false
          arch: amd64
          rootdir: ""
          workdir: ""

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.S3_CDN_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.S3_CDN_SECRET_KEY }}
          aws-region: us-east-1

      - name: CI Setup
        uses: ./.github/actions/ci-setup

      - name: Configure NPM
        uses: ./.github/actions/npm-config
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}

      - name: Bump and Collect Version
        run: |
          pnpm changeset version
          echo "BUILD_VERSION=$(sed -nE 's/^\s*"version": "(.*?)",$/\1/p' design-system/react/package.json)" >> $GITHUB_ENV
          git reset --hard
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup git user (for changelog step)
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Build
        run: pnpm build

      - name: Create Release Pull Request or Publish to NPM
        id: changesets
        uses: FuelLabs/changesets-action@main
        with:
          publish: pnpm changeset:release
          commit: "ci(changesets): versioning packages"
          title: "ci(changesets): versioning packages"
          createGithubReleases: aggregate
          githubReleaseName: v${{ env.BUILD_VERSION }}
          githubTagName: v${{ env.BUILD_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Release to @dev tag
        if: steps.changesets.outputs.published != 'true'
        run: |
          git checkout master
          pnpm changeset version --snapshot dev
          pnpm changeset publish --tag dev
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy CDN Assets
        run: |
          aws s3 cp fonts/ s3://${S3_CDN_BUCKET} --recursive
          aws cloudfront create-invalidation --distribution-id $S3_CDN_ID --paths '/*'
        env:
          S3_CDN_BUCKET: ${{ secrets.S3_CDN_BUCKET }}
          S3_CDN_ID: ${{ secrets.S3_CDN_ID }}
